# Generated by Django 2.0.7 on 2018-08-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cstask', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
    ]
